#pragma once

enum DIR	{ DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_END };	

enum OBJID{ OBJ_BUTTON, OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_SHIELD, OBJ_END};

enum RENDERID { BACKGROUND, GAMEOBJECT, EFFECT, UI, RENDER_END };

enum SCENEID { SCENE_LOGO, SCENE_MENU, SCENE_EDIT, SCENE_STAGE, SCENE_END };

 // 최대 32 채널까지 동시 재생이 가능
enum CHANNELID { SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, SOUND_EFFECT, SOUND_UI, MAXCHANNEL };